//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.24 at 09:26:48 AM CET 
//


package indexer.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import indexer.config.FieldType;
import indexer.config.IndexType;
import indexer.config.VectorType;


/**
 * <p>Java class for FieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Index" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="Store" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Termvector" type="{http://aid.org/}vectorType" minOccurs="0"/>
 *         &lt;element name="FieldAnalyzer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldType", propOrder = {
    "index",
    "store",
    "termvector",
    "fieldAnalyzer",
    "description"
})
public class FieldType {

    @XmlElement(name = "Index", namespace = "http://aid.org/")
    protected IndexType index;
    @XmlElement(name = "Store", namespace = "http://aid.org/")
    protected Boolean store;
    @XmlElement(name = "Termvector", namespace = "http://aid.org/")
    protected VectorType termvector;
    @XmlElement(name = "FieldAnalyzer", namespace = "http://aid.org/")
    protected String fieldAnalyzer;
    @XmlElement(name = "Description", namespace = "http://aid.org/")
    protected String description;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setIndex(IndexType value) {
        this.index = value;
    }

    /**
     * Gets the value of the store property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStore() {
        return store;
    }

    /**
     * Sets the value of the store property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStore(Boolean value) {
        this.store = value;
    }

    /**
     * Gets the value of the termvector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getTermvector() {
        return termvector;
    }

    /**
     * Sets the value of the termvector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setTermvector(VectorType value) {
        this.termvector = value;
    }

    /**
     * Gets the value of the fieldAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldAnalyzer() {
        return fieldAnalyzer;
    }

    /**
     * Sets the value of the fieldAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldAnalyzer(String value) {
        this.fieldAnalyzer = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
