//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.24 at 09:26:48 AM CET 
//


package indexer.config;

import javax.xml.bind.annotation.XmlEnum;
import indexer.config.IndexType;


/**
 * <p>Java class for indexType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="indexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="NO_NORMS"/>
 *     &lt;enumeration value="TOKENIZED"/>
 *     &lt;enumeration value="UNTOKENIZED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum IndexType {

    NO,
    NO_NORMS,
    TOKENIZED,
    UNTOKENIZED;

    public String value() {
        return name();
    }

    public IndexType fromValue(String v) {
        return valueOf(v);
    }

}
