//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.17 at 01:35:22 PM CET 
//


package indexer.config;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import indexer.config.AnalyzerType;
import indexer.config.FieldType;
import indexer.config.IndexType;
import indexer.config.VectorType;


/**
 * <p>Java class for FieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TitleIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="TitleStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TitleTermvector" type="{http://aid.org/}vectorType" minOccurs="0"/>
 *         &lt;element name="AuthorIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="AuthorStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="FirstAuthorIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="FirstAuthorStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AbstractIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="AbstractStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AbstractTermvector" type="{http://aid.org/}vectorType" minOccurs="0"/>
 *         &lt;element name="PathIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="PathStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContentsIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="ContentsStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContentsTermvector" type="{http://aid.org/}vectorType" minOccurs="0"/>
 *         &lt;element name="DateIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="URLIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="URLStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IDIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="IndexStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PublishedInIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="PublishedInStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="KeywordsIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="KeywordsStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MetaDataIndex" type="{http://aid.org/}indexType" minOccurs="0"/>
 *         &lt;element name="MetaDataStore" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MetaDataTermvector" type="{http://aid.org/}vectorType" minOccurs="0"/>
 *         &lt;element name="FieldAnalyzer" type="{http://aid.org/}analyzerType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "FieldType", propOrder = {
    "titleIndex",
    "titleStore",
    "titleTermvector",
    "authorIndex",
    "authorStore",
    "firstAuthorIndex",
    "firstAuthorStore",
    "abstractIndex",
    "abstractStore",
    "abstractTermvector",
    "pathIndex",
    "pathStore",
    "contentsIndex",
    "contentsStore",
    "contentsTermvector",
    "dateIndex",
    "urlIndex",
    "urlStore",
    "idIndex",
    "indexStore",
    "publishedInIndex",
    "publishedInStore",
    "keywordsIndex",
    "keywordsStore",
    "metaDataIndex",
    "metaDataStore",
    "metaDataTermvector",
    "fieldAnalyzer"
})
public class FieldType {

    @XmlElement(name = "TitleIndex", namespace = "http://aid.org/")
    protected IndexType titleIndex;
    @XmlElement(name = "TitleStore", namespace = "http://aid.org/")
    protected Boolean titleStore;
    @XmlElement(name = "TitleTermvector", namespace = "http://aid.org/")
    protected VectorType titleTermvector;
    @XmlElement(name = "AuthorIndex", namespace = "http://aid.org/")
    protected IndexType authorIndex;
    @XmlElement(name = "AuthorStore", namespace = "http://aid.org/")
    protected Boolean authorStore;
    @XmlElement(name = "FirstAuthorIndex", namespace = "http://aid.org/")
    protected IndexType firstAuthorIndex;
    @XmlElement(name = "FirstAuthorStore", namespace = "http://aid.org/")
    protected Boolean firstAuthorStore;
    @XmlElement(name = "AbstractIndex", namespace = "http://aid.org/")
    protected IndexType abstractIndex;
    @XmlElement(name = "AbstractStore", namespace = "http://aid.org/")
    protected Boolean abstractStore;
    @XmlElement(name = "AbstractTermvector", namespace = "http://aid.org/")
    protected VectorType abstractTermvector;
    @XmlElement(name = "PathIndex", namespace = "http://aid.org/")
    protected IndexType pathIndex;
    @XmlElement(name = "PathStore", namespace = "http://aid.org/")
    protected Boolean pathStore;
    @XmlElement(name = "ContentsIndex", namespace = "http://aid.org/")
    protected IndexType contentsIndex;
    @XmlElement(name = "ContentsStore", namespace = "http://aid.org/")
    protected Boolean contentsStore;
    @XmlElement(name = "ContentsTermvector", namespace = "http://aid.org/")
    protected VectorType contentsTermvector;
    @XmlElement(name = "DateIndex", namespace = "http://aid.org/")
    protected IndexType dateIndex;
    @XmlElement(name = "URLIndex", namespace = "http://aid.org/")
    protected IndexType urlIndex;
    @XmlElement(name = "URLStore", namespace = "http://aid.org/")
    protected Boolean urlStore;
    @XmlElement(name = "IDIndex", namespace = "http://aid.org/")
    protected IndexType idIndex;
    @XmlElement(name = "IndexStore", namespace = "http://aid.org/")
    protected Boolean indexStore;
    @XmlElement(name = "PublishedInIndex", namespace = "http://aid.org/")
    protected IndexType publishedInIndex;
    @XmlElement(name = "PublishedInStore", namespace = "http://aid.org/")
    protected Boolean publishedInStore;
    @XmlElement(name = "KeywordsIndex", namespace = "http://aid.org/")
    protected IndexType keywordsIndex;
    @XmlElement(name = "KeywordsStore", namespace = "http://aid.org/")
    protected Boolean keywordsStore;
    @XmlElement(name = "MetaDataIndex", namespace = "http://aid.org/")
    protected IndexType metaDataIndex;
    @XmlElement(name = "MetaDataStore", namespace = "http://aid.org/")
    protected Boolean metaDataStore;
    @XmlElement(name = "MetaDataTermvector", namespace = "http://aid.org/")
    protected VectorType metaDataTermvector;
    @XmlElement(name = "FieldAnalyzer", namespace = "http://aid.org/")
    protected AnalyzerType fieldAnalyzer;
    @XmlAttribute(name = "Type")
    protected String type;

    /**
     * Gets the value of the titleIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getTitleIndex() {
        return titleIndex;
    }

    /**
     * Sets the value of the titleIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setTitleIndex(IndexType value) {
        this.titleIndex = value;
    }

    /**
     * Gets the value of the titleStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTitleStore() {
        return titleStore;
    }

    /**
     * Sets the value of the titleStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTitleStore(Boolean value) {
        this.titleStore = value;
    }

    /**
     * Gets the value of the titleTermvector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getTitleTermvector() {
        return titleTermvector;
    }

    /**
     * Sets the value of the titleTermvector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setTitleTermvector(VectorType value) {
        this.titleTermvector = value;
    }

    /**
     * Gets the value of the authorIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getAuthorIndex() {
        return authorIndex;
    }

    /**
     * Sets the value of the authorIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setAuthorIndex(IndexType value) {
        this.authorIndex = value;
    }

    /**
     * Gets the value of the authorStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAuthorStore() {
        return authorStore;
    }

    /**
     * Sets the value of the authorStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthorStore(Boolean value) {
        this.authorStore = value;
    }

    /**
     * Gets the value of the firstAuthorIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getFirstAuthorIndex() {
        return firstAuthorIndex;
    }

    /**
     * Sets the value of the firstAuthorIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setFirstAuthorIndex(IndexType value) {
        this.firstAuthorIndex = value;
    }

    /**
     * Gets the value of the firstAuthorStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFirstAuthorStore() {
        return firstAuthorStore;
    }

    /**
     * Sets the value of the firstAuthorStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFirstAuthorStore(Boolean value) {
        this.firstAuthorStore = value;
    }

    /**
     * Gets the value of the abstractIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getAbstractIndex() {
        return abstractIndex;
    }

    /**
     * Sets the value of the abstractIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setAbstractIndex(IndexType value) {
        this.abstractIndex = value;
    }

    /**
     * Gets the value of the abstractStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbstractStore() {
        return abstractStore;
    }

    /**
     * Sets the value of the abstractStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstractStore(Boolean value) {
        this.abstractStore = value;
    }

    /**
     * Gets the value of the abstractTermvector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getAbstractTermvector() {
        return abstractTermvector;
    }

    /**
     * Sets the value of the abstractTermvector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setAbstractTermvector(VectorType value) {
        this.abstractTermvector = value;
    }

    /**
     * Gets the value of the pathIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getPathIndex() {
        return pathIndex;
    }

    /**
     * Sets the value of the pathIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setPathIndex(IndexType value) {
        this.pathIndex = value;
    }

    /**
     * Gets the value of the pathStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPathStore() {
        return pathStore;
    }

    /**
     * Sets the value of the pathStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPathStore(Boolean value) {
        this.pathStore = value;
    }

    /**
     * Gets the value of the contentsIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getContentsIndex() {
        return contentsIndex;
    }

    /**
     * Sets the value of the contentsIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setContentsIndex(IndexType value) {
        this.contentsIndex = value;
    }

    /**
     * Gets the value of the contentsStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContentsStore() {
        return contentsStore;
    }

    /**
     * Sets the value of the contentsStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContentsStore(Boolean value) {
        this.contentsStore = value;
    }

    /**
     * Gets the value of the contentsTermvector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getContentsTermvector() {
        return contentsTermvector;
    }

    /**
     * Sets the value of the contentsTermvector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setContentsTermvector(VectorType value) {
        this.contentsTermvector = value;
    }

    /**
     * Gets the value of the dateIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getDateIndex() {
        return dateIndex;
    }

    /**
     * Sets the value of the dateIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setDateIndex(IndexType value) {
        this.dateIndex = value;
    }

    /**
     * Gets the value of the urlIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getURLIndex() {
        return urlIndex;
    }

    /**
     * Sets the value of the urlIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setURLIndex(IndexType value) {
        this.urlIndex = value;
    }

    /**
     * Gets the value of the urlStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isURLStore() {
        return urlStore;
    }

    /**
     * Sets the value of the urlStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setURLStore(Boolean value) {
        this.urlStore = value;
    }

    /**
     * Gets the value of the idIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getIDIndex() {
        return idIndex;
    }

    /**
     * Sets the value of the idIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setIDIndex(IndexType value) {
        this.idIndex = value;
    }

    /**
     * Gets the value of the indexStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndexStore() {
        return indexStore;
    }

    /**
     * Sets the value of the indexStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndexStore(Boolean value) {
        this.indexStore = value;
    }

    /**
     * Gets the value of the publishedInIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getPublishedInIndex() {
        return publishedInIndex;
    }

    /**
     * Sets the value of the publishedInIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setPublishedInIndex(IndexType value) {
        this.publishedInIndex = value;
    }

    /**
     * Gets the value of the publishedInStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPublishedInStore() {
        return publishedInStore;
    }

    /**
     * Sets the value of the publishedInStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublishedInStore(Boolean value) {
        this.publishedInStore = value;
    }

    /**
     * Gets the value of the keywordsIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getKeywordsIndex() {
        return keywordsIndex;
    }

    /**
     * Sets the value of the keywordsIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setKeywordsIndex(IndexType value) {
        this.keywordsIndex = value;
    }

    /**
     * Gets the value of the keywordsStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeywordsStore() {
        return keywordsStore;
    }

    /**
     * Sets the value of the keywordsStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeywordsStore(Boolean value) {
        this.keywordsStore = value;
    }

    /**
     * Gets the value of the metaDataIndex property.
     * 
     * @return
     *     possible object is
     *     {@link IndexType }
     *     
     */
    public IndexType getMetaDataIndex() {
        return metaDataIndex;
    }

    /**
     * Sets the value of the metaDataIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexType }
     *     
     */
    public void setMetaDataIndex(IndexType value) {
        this.metaDataIndex = value;
    }

    /**
     * Gets the value of the metaDataStore property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMetaDataStore() {
        return metaDataStore;
    }

    /**
     * Sets the value of the metaDataStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMetaDataStore(Boolean value) {
        this.metaDataStore = value;
    }

    /**
     * Gets the value of the metaDataTermvector property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType }
     *     
     */
    public VectorType getMetaDataTermvector() {
        return metaDataTermvector;
    }

    /**
     * Sets the value of the metaDataTermvector property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType }
     *     
     */
    public void setMetaDataTermvector(VectorType value) {
        this.metaDataTermvector = value;
    }

    /**
     * Gets the value of the fieldAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyzerType }
     *     
     */
    public AnalyzerType getFieldAnalyzer() {
        return fieldAnalyzer;
    }

    /**
     * Sets the value of the fieldAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyzerType }
     *     
     */
    public void setFieldAnalyzer(AnalyzerType value) {
        this.fieldAnalyzer = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
