//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.17 at 01:35:22 PM CET 
//


package indexer.config;

import javax.xml.bind.annotation.XmlEnum;
import indexer.config.VectorType;


/**
 * <p>Java class for vectorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="vectorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="YES"/>
 *     &lt;enumeration value="WITH_OFFSETS"/>
 *     &lt;enumeration value="WITH_POSITIONS"/>
 *     &lt;enumeration value="WITH_POSITIONS_OFFSETS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum VectorType {

    NO,
    WITH_OFFSETS,
    WITH_POSITIONS,
    WITH_POSITIONS_OFFSETS,
    YES;

    public String value() {
        return name();
    }

    public VectorType fromValue(String v) {
        return valueOf(v);
    }

}
