//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.28 at 01:11:10 PM CET 
//


package config.aid.org;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the config.aid.org package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends config.aid.org.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static config.aid.org.impl.runtime.GrammarInfo grammarInfo = new config.aid.org.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (config.aid.org.ObjectFactory.class));
    public final static java.lang.Class version = (config.aid.org.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((config.aid.org.Config.class), "config.aid.org.impl.ConfigImpl");
        defaultImplementations.put((config.aid.org.DocType.class), "config.aid.org.impl.DocTypeImpl");
        defaultImplementations.put((config.aid.org.FieldType.class), "config.aid.org.impl.FieldTypeImpl");
        defaultImplementations.put((config.aid.org.ConfigType.class), "config.aid.org.impl.ConfigTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://aid.org/", "config"), (config.aid.org.Config.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: config.aid.org
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Config
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public config.aid.org.Config createConfig()
        throws javax.xml.bind.JAXBException
    {
        return new config.aid.org.impl.ConfigImpl();
    }

    /**
     * Create an instance of DocType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public config.aid.org.DocType createDocType()
        throws javax.xml.bind.JAXBException
    {
        return new config.aid.org.impl.DocTypeImpl();
    }

    /**
     * Create an instance of FieldType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public config.aid.org.FieldType createFieldType()
        throws javax.xml.bind.JAXBException
    {
        return new config.aid.org.impl.FieldTypeImpl();
    }

    /**
     * Create an instance of ConfigType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public config.aid.org.ConfigType createConfigType()
        throws javax.xml.bind.JAXBException
    {
        return new config.aid.org.impl.ConfigTypeImpl();
    }

}
