//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.28 at 01:11:10 PM CET 
//


package config.aid.org;


/**
 * Java content class for configType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/java/Indexer/config.xsd line 20)
 * <p>
 * <pre>
 * &lt;complexType name="configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndexPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndexOverwrite" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IndexAnalyzer" type="{http://aid.org/}analyzerType" minOccurs="0"/>
 *         &lt;element name="DataPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SRBused" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MergeFactor" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MinMergeDocs" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DocType" type="{http://aid.org/}docType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Creator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MetaData" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ConfigType {


    /**
     * Gets the value of the mergeFactor property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger}
     */
    java.math.BigInteger getMergeFactor();

    /**
     * Sets the value of the mergeFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger}
     */
    void setMergeFactor(java.math.BigInteger value);

    /**
     * Gets the value of the minMergeDocs property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger}
     */
    java.math.BigInteger getMinMergeDocs();

    /**
     * Sets the value of the minMergeDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger}
     */
    void setMinMergeDocs(java.math.BigInteger value);

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMetaData();

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMetaData(java.lang.String value);

    /**
     * Gets the value of the indexPath property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIndexPath();

    /**
     * Sets the value of the indexPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIndexPath(java.lang.String value);

    /**
     * Gets the value of the srBused property.
     * 
     */
    boolean isSRBused();

    /**
     * Sets the value of the srBused property.
     * 
     */
    void setSRBused(boolean value);

    /**
     * Gets the value of the DocType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the DocType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link config.aid.org.DocType}
     * 
     */
    java.util.List getDocType();

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDataPath();

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDataPath(java.lang.String value);

    /**
     * Gets the value of the indexAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIndexAnalyzer();

    /**
     * Sets the value of the indexAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIndexAnalyzer(java.lang.String value);

    /**
     * Gets the value of the indexOverwrite property.
     * 
     */
    boolean isIndexOverwrite();

    /**
     * Sets the value of the indexOverwrite property.
     * 
     */
    void setIndexOverwrite(boolean value);

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCreator();

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCreator(java.lang.String value);

}
