//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.28 at 01:11:10 PM CET 
//


package config.aid.org;


/**
 * Java content class for config element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/java/Indexer/config.xsd line 18)
 * <p>
 * <pre>
 * &lt;element name="config" type="{http://aid.org/}configType"/>
 * </pre>
 * 
 */
public interface Config
    extends javax.xml.bind.Element, config.aid.org.ConfigType
{


}
