//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.03.24 at 09:26:48 AM CET 
//


package indexer.config;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import indexer.config.ConfigType;
import indexer.config.DocType;


/**
 * <p>Java class for configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IndexOverwrite" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IndexAnalyzer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DataPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SRBused" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MergeFactor" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MaxBufferedDocs" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DocType" type="{http://aid.org/}docType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Creator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MetaData" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configType", propOrder = {
    "name",
    "indexOverwrite",
    "indexAnalyzer",
    "dataPath",
    "srBused",
    "mergeFactor",
    "maxBufferedDocs",
    "docType"
})
public class ConfigType {

    @XmlElement(name = "Name", namespace = "http://aid.org/")
    protected String name;
    @XmlElement(name = "IndexOverwrite", namespace = "http://aid.org/")
    protected Boolean indexOverwrite;
    @XmlElement(name = "IndexAnalyzer", namespace = "http://aid.org/")
    protected String indexAnalyzer;
    @XmlElement(name = "DataPath", namespace = "http://aid.org/")
    protected String dataPath;
    @XmlElement(name = "SRBused", namespace = "http://aid.org/")
    protected Boolean srBused;
    @XmlElement(name = "MergeFactor", namespace = "http://aid.org/")
    protected BigInteger mergeFactor;
    @XmlElement(name = "MaxBufferedDocs", namespace = "http://aid.org/")
    protected BigInteger maxBufferedDocs;
    @XmlElement(name = "DocType", namespace = "http://aid.org/")
    protected List<DocType> docType;
    @XmlAttribute(name = "Creator")
    protected String creator;
    @XmlAttribute(name = "MetaData")
    protected String metaData;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the indexOverwrite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndexOverwrite() {
        return indexOverwrite;
    }

    /**
     * Sets the value of the indexOverwrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndexOverwrite(Boolean value) {
        this.indexOverwrite = value;
    }

    /**
     * Gets the value of the indexAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexAnalyzer() {
        return indexAnalyzer;
    }

    /**
     * Sets the value of the indexAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexAnalyzer(String value) {
        this.indexAnalyzer = value;
    }

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPath(String value) {
        this.dataPath = value;
    }

    /**
     * Gets the value of the srBused property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSRBused() {
        return srBused;
    }

    /**
     * Sets the value of the srBused property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSRBused(Boolean value) {
        this.srBused = value;
    }

    /**
     * Gets the value of the mergeFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMergeFactor() {
        return mergeFactor;
    }

    /**
     * Sets the value of the mergeFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMergeFactor(BigInteger value) {
        this.mergeFactor = value;
    }

    /**
     * Gets the value of the maxBufferedDocs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxBufferedDocs() {
        return maxBufferedDocs;
    }

    /**
     * Sets the value of the maxBufferedDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxBufferedDocs(BigInteger value) {
        this.maxBufferedDocs = value;
    }

    /**
     * Gets the value of the docType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocType }
     * 
     * 
     */
    public List<DocType> getDocType() {
        if (docType == null) {
            docType = new ArrayList<DocType>();
        }
        return this.docType;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaData(String value) {
        this.metaData = value;
    }

}
