//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.28 at 01:11:10 PM CET 
//


package config.aid.org.impl;

public class ConfigImpl
    extends config.aid.org.impl.ConfigTypeImpl
    implements config.aid.org.Config, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, config.aid.org.impl.runtime.UnmarshallableObject, config.aid.org.impl.runtime.XMLSerializable, config.aid.org.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (config.aid.org.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (config.aid.org.Config.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "http://aid.org/";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "config";
    }

    public config.aid.org.impl.runtime.UnmarshallingEventHandler createUnmarshaller(config.aid.org.impl.runtime.UnmarshallingContext context) {
        return new config.aid.org.impl.ConfigImpl.Unmarshaller(context);
    }

    public void serializeBody(config.aid.org.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://aid.org/", "config");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(config.aid.org.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(config.aid.org.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (config.aid.org.Config.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsr\u0000\u001dc"
+"om.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsq\u0000~\u0000\u0000sr\u0000\u0011jav"
+"a.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0007ppsr\u0000\u001bcom.sun.ms"
+"v.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Da"
+"tatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;"
+"xq\u0000~\u0000\u0004ppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000"
+"\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\f"
+"namespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000!L\u0000\nwhiteSpa"
+"cet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http"
+"://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatyp"
+"e.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv"
+".datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.m"
+"sv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004ppsr"
+"\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000!L\u0000\f"
+"namespaceURIq\u0000~\u0000!xpq\u0000~\u0000%q\u0000~\u0000$sq\u0000~\u0000\u0013ppsr\u0000 com.sun.msv.grammar"
+".AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004q\u0000"
+"~\u0000\u0017psq\u0000~\u0000\u0019ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0000xq\u0000~\u0000\u001eq\u0000~\u0000$t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceP"
+"rocessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\'q\u0000~\u0000*sq\u0000~\u0000+q\u0000~\u00003q\u0000~\u0000$sr\u0000#c"
+"om.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~"
+"\u0000!L\u0000\fnamespaceURIq\u0000~\u0000!xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instances"
+"r\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u0000\u0016\u0001psq\u0000~\u00007t\u0000\tIndexPatht\u0000\u000fhttp://aid.org/q\u0000~\u0000=sq\u0000"
+"~\u0000\u0013ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0019ppsr\u0000$com.sun.msv.datatype.x"
+"sd.BooleanType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001eq\u0000~\u0000$t\u0000\u0007booleanq\u0000~\u00005q\u0000~\u0000*sq\u0000~"
+"\u0000+q\u0000~\u0000Hq\u0000~\u0000$sq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000eInde"
+"xOverwriteq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0019ppsr\u0000"
+")com.sun.msv.datatype.xsd.EnumerationFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valu"
+"est\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.datatype.xsd.DataTypeWit"
+"hValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd"
+".DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueChec"
+"kFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;"
+"L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\t"
+"facetNameq\u0000~\u0000!xq\u0000~\u0000 q\u0000~\u0000At\u0000\fanalyzerTypeq\u0000~\u0000(\u0000\u0000q\u0000~\u0000#q\u0000~\u0000#t\u0000\u000b"
+"enumerationsr\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0004t"
+"\u0000\bSTANDARDt\u0000\u0004STOPt\u0000\u0006SIMPLEt\u0000\nWHITESPACExq\u0000~\u0000*sq\u0000~\u0000+q\u0000~\u0000Yq\u0000~\u0000"
+"Asq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\rIndexAnalyzerq\u0000"
+"~\u0000Aq\u0000~\u0000=sq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000\u001csq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009"
+"q\u0000~\u0000=sq\u0000~\u00007t\u0000\bDataPathq\u0000~\u0000Asq\u0000~\u0000\u0013ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000"
+"Esq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0007SRBusedq\u0000~\u0000Aq\u0000~"
+"\u0000=sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0019ppsr\u0000$com.sun.msv.datat"
+"ype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.I"
+"ntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetsq\u0000~\u0000Vxq\u0000~\u0000\u001eq\u0000~\u0000$t\u0000\u0007"
+"integerq\u0000~\u00005sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWith"
+"LexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000Uppq\u0000~\u00005\u0001\u0000sr\u0000#com.sun."
+"msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001eq\u0000~\u0000$t\u0000\u0007decimalq"
+"\u0000~\u00005q\u0000~\u0000\u007ft\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000*sq\u0000~\u0000+q\u0000~\u0000zq\u0000~\u0000$sq\u0000~\u0000\u0013pps"
+"q\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u000bMergeFactorq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~"
+"\u0000\u0013ppsq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppq\u0000~\u0000vsq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009"
+"q\u0000~\u0000=sq\u0000~\u00007t\u0000\fMinMergeDocsq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000\u0013ppsr\u0000 com.sun.msv."
+"grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.Unary"
+"Exp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004q\u0000~\u0000\u0017psq\u0000~\u0000\u0000q\u0000~\u0000\u0017p\u0000sq\u0000~\u0000\u0007ppsq"
+"\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000\u0013ppsq\u0000~\u0000\u008fq\u0000~\u0000\u0017psq\u0000~\u0000.q\u0000~\u0000\u0017psr\u00002com.sun.msv.gramm"
+"ar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004q\u0000~\u0000>psr\u0000 "
+"com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00008q\u0000~\u0000=sq\u0000~\u00007"
+"t\u0000\u0016config.aid.org.DocTypet\u0000+http://java.sun.com/jaxb/xjc/dum"
+"my-elementssq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0007DocTy"
+"peq\u0000~\u0000Aq\u0000~\u0000=sq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u0000\u001csq\u0000~\u00007t\u0000\u0007Creatort\u0000\u0000q\u0000~\u0000"
+"=sq\u0000~\u0000\u0013ppsq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u0000\u001csq\u0000~\u00007t\u0000\bMetaDataq\u0000~\u0000\u00a7q\u0000~\u0000=sq\u0000~\u0000\u0013p"
+"psq\u0000~\u0000.q\u0000~\u0000\u0017pq\u0000~\u00000q\u0000~\u00009q\u0000~\u0000=sq\u0000~\u00007t\u0000\u0006configq\u0000~\u0000Asr\u0000\"com.sun."
+"msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/"
+"msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.gram"
+"mar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVer"
+"sionL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\'\u0001p"
+"q\u0000~\u0000\u0091q\u0000~\u0000\tq\u0000~\u0000\u0093q\u0000~\u0000-q\u0000~\u0000Jq\u0000~\u0000bq\u0000~\u0000hq\u0000~\u0000oq\u0000~\u0000\u0083q\u0000~\u0000\u008aq\u0000~\u0000\u0095q\u0000~\u0000\u009f"
+"q\u0000~\u0000\u00acq\u0000~\u0000\u00a8q\u0000~\u0000Pq\u0000~\u0000sq\u0000~\u0000\u0087q\u0000~\u0000\u0012q\u0000~\u0000\rq\u0000~\u0000Dq\u0000~\u0000nq\u0000~\u0000\nq\u0000~\u0000uq\u0000~\u0000\u0089"
+"q\u0000~\u0000Bq\u0000~\u0000lq\u0000~\u0000\u000eq\u0000~\u0000\u000fq\u0000~\u0000Nq\u0000~\u0000\u0011q\u0000~\u0000\u0010q\u0000~\u0000\u0014q\u0000~\u0000\u000bq\u0000~\u0000\u008eq\u0000~\u0000\u0018q\u0000~\u0000g"
+"q\u0000~\u0000\u00a3q\u0000~\u0000\fq\u0000~\u0000\u0096x"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends config.aid.org.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(config.aid.org.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(config.aid.org.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return config.aid.org.impl.ConfigImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("config" == ___local)&&("http://aid.org/" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "Creator");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MetaData");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("IndexPath" == ___local)&&("http://aid.org/" == ___uri)) {
                            spawnHandlerFromEnterElement((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("IndexOverwrite" == ___local)&&("http://aid.org/" == ___uri)) {
                            spawnHandlerFromEnterElement((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("IndexAnalyzer" == ___local)&&("http://aid.org/" == ___uri)) {
                            spawnHandlerFromEnterElement((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("DataPath" == ___local)&&("http://aid.org/" == ___uri)) {
                            spawnHandlerFromEnterElement((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("config" == ___local)&&("http://aid.org/" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "Creator");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MetaData");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("Creator" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        if (("MetaData" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((config.aid.org.impl.ConfigTypeImpl)config.aid.org.impl.ConfigImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "Creator");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        attIdx = context.getAttribute("", "MetaData");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "Creator");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            attIdx = context.getAttribute("", "MetaData");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
